# 1, Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1 

In [2]:
import numpy as np
arr_zeros = np.zeros(10, dtype = int)
arr_zeros[4] = 1
arr_zeros

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

# 2, Tạo arr_h có giá trị từ 10 đến 24. In danh sách các phần tử theo thứ tự đảo ngược của arr_h

In [4]:
arr_h = np.arange(10,25)
arr_h_reversed = arr_h[::-1]
print(arr_h)
print("Các phần tử đảo ngược của arr_h: ", arr_h_reversed)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Các phần tử đảo ngược của arr_h:  [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# 3, Cho arr_k = np.array([1,2,0,8,2,0,1,3,0,5,0]), tạo arr_1 từ arr_k với các phần tử khác 0 

In [5]:
arr_k = np.array([1,2,0,8,2,0,1,3,0,5,0])
arr_1 = arr_k[arr_k != 0]
print(arr_1)

[1 2 8 2 1 3 5]


# 4, Từ arr_k của câu 3, thêm 2 phần tử có giá trị 10 và 20 vào cuối array

In [6]:
arr_k_add = np.append(arr_k, [10,20])
arr_k_add

array([ 1,  2,  0,  8,  2,  0,  1,  3,  0,  5,  0, 10, 20])

# 5, Từ arr của câu 4 thêm phần tử có giá trị 100 vào vị trí có index = 5 

In [7]:
arr_k_100 = np.insert(arr_k_add, 5, 100)
arr_k_100

array([  1,   2,   0,   8,   2, 100,   0,   1,   3,   0,   5,   0,  10,
        20])

# 6, Từ arr của câu 5, xóa các phần tử tại ví trí có index = 0,1,2

In [8]:
arr_delete = np.delete(arr_k_100, [0,1,2])
arr_delete

array([  8,   2, 100,   0,   1,   3,   0,   5,   0,  10,  20])